import assert from "node:assert/strict";
import { mkdtemp, rm } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { spawn } from "node:child_process";
import pg from "pg";
import { migrateSessionOwnership } from "../../../src/db/migrations/session-ownership.js";

if (process.env.WQT_RUNTIME_TEST_CHILD !== "1")
  throw new Error("owned recovery harness required");

function txFor(client) {
  const sql = (text) => {
    let i = 0;
    return text.replace(/\?/g, () => `$${++i}`);
  };
  return {
    run: (text, params) => client.query(sql(text), params),
    get: async (text, params) =>
      (await client.query(sql(text), params)).rows[0] ?? null,
  };
}

function commandEnv(url) {
  const parsed = new URL(url);
  const env = {
    NODE_ENV: "test",
    PATH: process.env.PATH,
    Path: process.env.Path,
    SystemRoot: process.env.SystemRoot,
    WINDIR: process.env.WINDIR,
    TEMP: process.env.TEMP,
    TMP: process.env.TMP,
    PATHEXT: process.env.PATHEXT,
    ComSpec: process.env.ComSpec,
  };
  if (parsed.password) env.PGPASSWORD = decodeURIComponent(parsed.password);
  env.PGCONNECT_TIMEOUT = "5";
  return Object.fromEntries(
    Object.entries(env).filter(([, value]) => value !== undefined),
  );
}

function pgArgs(url) {
  const parsed = new URL(url);
  return [
    "-h",
    parsed.hostname,
    "-p",
    parsed.port || "5432",
    "-U",
    decodeURIComponent(parsed.username),
    "-d",
    decodeURIComponent(parsed.pathname.slice(1)),
  ];
}

async function runTool(tool, args, url) {
  const child = spawn(tool, args, {
    shell: false,
    windowsHide: true,
    env: commandEnv(url),
    stdio: ["ignore", "ignore", "pipe"],
  });
  child.stderr.resume();
  const result = await new Promise((resolve, reject) => {
    const timer = setTimeout(() => child.kill("SIGKILL"), 20000);
    child.once("error", (error) => {
      clearTimeout(timer);
      reject(error);
    });
    child.once("close", (code, signal) => {
      clearTimeout(timer);
      resolve({ code, signal });
    });
  });
  if (result.code !== 0)
    throw new Error(
      `${tool} failed (${result.code ?? result.signal ?? "unavailable"})`,
    );
}

async function assertTool(tool) {
  try {
    await runTool(tool, ["--version"], process.env.WQT_RECOVERY_SOURCE_URL);
  } catch (error) {
    throw new Error(`${tool} is required for PostgreSQL recovery tests`);
  }
}

async function connect(url) {
  const client = new pg.Client({
    connectionString: url,
    connectionTimeoutMillis: 5000,
  });
  try {
    await client.connect();
    return client;
  } catch (error) {
    await client.end().catch(() => {});
    throw error;
  }
}
async function schemaFixture(client) {
  await client.query(
    "CREATE TABLE organizations (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, owner_user_id BIGINT, valid_until BIGINT)",
  );
  await client.query(
    "CREATE TABLE users (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username TEXT UNIQUE, enterprise_id BIGINT)",
  );
  await client.query(
    "CREATE TABLE game_sessions (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id BIGINT NOT NULL, started_at BIGINT)",
  );
  await client.query(
    "INSERT INTO organizations(name, owner_user_id, valid_until) VALUES ('restore-org', 0, 4102444800000)",
  );
  await client.query(
    "INSERT INTO users(username, enterprise_id) VALUES ('historical-user', 1)",
  );
  await client.query(
    "INSERT INTO game_sessions(user_id, started_at) VALUES (1, 1700000000000)",
  );
}

export async function runRecoveryScenario() {
  const sourceUrl = process.env.WQT_RECOVERY_SOURCE_URL;
  const restoreUrl = process.env.WQT_RECOVERY_RESTORE_URL;
  const finalUrl = process.env.WQT_RECOVERY_FINAL_URL;
  if (!sourceUrl || !restoreUrl || !finalUrl)
    throw new Error("owned recovery URLs are required");
  await assertTool("pg_dump");
  await assertTool("pg_restore");
  let tempDir;
  let source;
  let restore;
  let final;
  try {
    tempDir = await mkdtemp(path.join(os.tmpdir(), "wqt-recovery-"));
    const beforeDump = path.join(tempDir, "before.dump");
    const afterDump = path.join(tempDir, "after.dump");
    source = await connect(sourceUrl);
    restore = await connect(restoreUrl);
    final = await connect(finalUrl);
    await schemaFixture(source);
    await runTool(
      "pg_dump",
      [...pgArgs(sourceUrl), "-Fc", "-f", beforeDump],
      sourceUrl,
    );
    const sourceTx = txFor(source);
    await source.query("BEGIN");
    await migrateSessionOwnership(sourceTx);
    await source.query("COMMIT");
    assert.deepEqual(
      (
        await source.query(
          "SELECT organization_id, ownership_kind FROM game_sessions WHERE id=1",
        )
      ).rows,
      [{ organization_id: null, ownership_kind: "legacy_unknown" }],
    );
    await runTool(
      "pg_restore",
      [...pgArgs(restoreUrl), "--exit-on-error", "--no-owner", beforeDump],
      restoreUrl,
    );
    for (const table of ["organizations", "users"]) {
      assert.deepEqual(
        (await restore.query(`SELECT * FROM ${table} ORDER BY id`)).rows,
        (await source.query(`SELECT * FROM ${table} ORDER BY id`)).rows,
      );
    }
    const oldColumns = await restore.query(
      "SELECT column_name FROM information_schema.columns WHERE table_name='game_sessions' ORDER BY ordinal_position",
    );
    assert.deepEqual(
      oldColumns.rows.map((r) => r.column_name),
      ["id", "user_id", "started_at"],
    );
    const old = await restore.query(
      "SELECT user_id, started_at FROM game_sessions",
    );
    assert.deepEqual(old.rows, [{ user_id: "1", started_at: "1700000000000" }]);
    const tx = txFor(restore);
    await restore.query("BEGIN");
    await migrateSessionOwnership(tx);
    await restore.query("COMMIT");
    await restore.query("BEGIN");
    await migrateSessionOwnership(tx);
    await restore.query("COMMIT");
    const migrated = await restore.query(
      "SELECT organization_id, ownership_kind FROM game_sessions WHERE id=1",
    );
    assert.deepEqual(migrated.rows, [
      { organization_id: null, ownership_kind: "legacy_unknown" },
    ]);
    await restore.query(
      "INSERT INTO organizations(name, owner_user_id, valid_until) VALUES ('new-org', 0, 4102444800000)",
    );
    await restore.query(
      "INSERT INTO game_sessions(user_id, started_at, organization_id, ownership_kind) VALUES (1, 1700000001000, 2, 'organization')",
    );
    await restore.query(
      "INSERT INTO session_files(id, session_id, user_id, object_key, filename, media_type, size, created_at) VALUES ('00000000-0000-0000-0000-000000000001', 2, 1, 'private/key', 'private.txt', 'text/plain', 4, 1700000001000)",
    );
    await assert.rejects(
      () =>
        restore.query("UPDATE game_sessions SET organization_id=1 WHERE id=2"),
      /immutable/i,
    );
    const expectedSessions = (
      await restore.query("SELECT * FROM game_sessions ORDER BY id")
    ).rows;
    const expectedFiles = (
      await restore.query("SELECT * FROM session_files ORDER BY id")
    ).rows;
    await runTool(
      "pg_dump",
      [...pgArgs(restoreUrl), "-Fc", "-f", afterDump],
      restoreUrl,
    );
    await runTool(
      "pg_restore",
      [...pgArgs(finalUrl), "--exit-on-error", "--no-owner", afterDump],
      finalUrl,
    );
    assert.deepEqual(
      (await final.query("SELECT * FROM game_sessions ORDER BY id")).rows,
      expectedSessions,
    );
    assert.deepEqual(
      (await final.query("SELECT * FROM session_files ORDER BY id")).rows,
      expectedFiles,
    );
    assert.deepEqual(
      (
        await final.query(
          "SELECT organization_id, ownership_kind FROM game_sessions ORDER BY id",
        )
      ).rows,
      [
        { organization_id: null, ownership_kind: "legacy_unknown" },
        { organization_id: "2", ownership_kind: "organization" },
      ],
    );
    assert.deepEqual(
      (
        await final.query(
          "SELECT object_key, filename, media_type, size FROM session_files",
        )
      ).rows,
      [
        {
          object_key: "private/key",
          filename: "private.txt",
          media_type: "text/plain",
          size: "4",
        },
      ],
    );
    await assert.rejects(
      () =>
        final.query("UPDATE game_sessions SET organization_id=1 WHERE id=2"),
      /immutable/i,
    );
    await assert.rejects(
      () =>
        final.query(
          "INSERT INTO game_sessions(user_id, started_at, organization_id, ownership_kind) VALUES (1, 1, 999, 'organization')",
        ),
      /foreign key/i,
    );
    await assert.rejects(
      () =>
        final.query(
          "INSERT INTO game_sessions(user_id, started_at, ownership_kind) VALUES (1, 1, 'organization')",
        ),
      /check/i,
    );
    await assert.rejects(
      () =>
        final.query(
          "INSERT INTO session_files(id, session_id, user_id, object_key, filename, media_type, size, created_at) VALUES ('00000000-0000-0000-0000-000000000002', 2, 1, 'private/key', 'x', 'text/plain', 0, 1)",
        ),
      /unique/i,
    );
    console.log("RECOVERY_SCENARIO_PASSED");
  } finally {
    await Promise.allSettled(
      [source?.end(), restore?.end(), final?.end()].filter(Boolean),
    );
    if (tempDir) {
      const target = path.resolve(tempDir);
      if (
        path.dirname(target) !== path.resolve(os.tmpdir()) ||
        !path.basename(target).startsWith("wqt-recovery-")
      )
        throw new Error("Refusing cleanup outside owned temporary directory");
      await rm(target, { recursive: true, force: true });
    }
  }
}
