import sqlite3 from "sqlite3";
import fs from "fs";
import path from "path";
import { makePgApi, createPool } from "./sql-pg.js";

const NOW_MS = "(extract(epoch from now())*1000)::bigint";

/**
 * 卡牌数据源接口定义
 * 所有数据源（SQLite, PostgreSQL, Feishu等）必须实现以下方法
 */
class ICardsSource {
    async init() { throw new Error("Method not implemented"); }
    async run(sql, params) { throw new Error("Method not implemented"); }
    async get(sql, params) { throw new Error("Method not implemented"); }
    async all(sql, params) { throw new Error("Method not implemented"); }
    async close() {}
}

/**
 * PostgreSQL 数据源实现（与主库可共用同一个 database，表名不冲突）
 */
class PostgresCardsSource extends ICardsSource {
    constructor(connectionString) {
        super();
        this.connectionString = connectionString;
        this.api = null;
    }

    async init() {
        this.pool = createPool(this.connectionString);
        this.api = makePgApi(this.pool);

        await this.run(`
      CREATE TABLE IF NOT EXISTS cards (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        key BIGINT UNIQUE NOT NULL,
        safety_type TEXT NOT NULL,
        event TEXT NOT NULL,
        phase TEXT,
        options_json TEXT NOT NULL,
        status TEXT DEFAULT 'pending',
        version INTEGER DEFAULT 1,
        version_label TEXT,
        audio_url TEXT,
        attribute_reason TEXT,
        notes TEXT,
        branch TEXT DEFAULT 'release',
        online_id TEXT,
        parent_id BIGINT,
        current_version_id BIGINT,
        author_id BIGINT,
        card_code TEXT,
        workbench TEXT DEFAULT '经典版',
        title TEXT,
        guide_text TEXT,
        subtopic TEXT,
        whitepaper_ref TEXT,
        trainer_material_json TEXT,
        created_at BIGINT NOT NULL DEFAULT ${NOW_MS},
        updated_at BIGINT,
        deleted_at BIGINT
      );
    `);

        await this.run(`
      CREATE TABLE IF NOT EXISTS card_versions (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        card_id BIGINT NOT NULL,
        key BIGINT NOT NULL,
        safety_type TEXT NOT NULL,
        event TEXT NOT NULL,
        phase TEXT,
        options_json TEXT NOT NULL,
        status TEXT DEFAULT 'pending',
        version INTEGER DEFAULT 1,
        version_label TEXT,
        attribute_reason TEXT,
        author_id BIGINT,
        audio_url TEXT,
        note TEXT,
        branch TEXT DEFAULT 'main',
        parent_id BIGINT,
        promoted_at BIGINT,
        card_code TEXT,
        workbench TEXT,
        title TEXT,
        guide_text TEXT,
        subtopic TEXT,
        whitepaper_ref TEXT,
        trainer_material_json TEXT,
        created_at BIGINT NOT NULL DEFAULT ${NOW_MS}
      );
    `);

        await this.run(`
      CREATE TABLE IF NOT EXISTS cards_released (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        card_id BIGINT NOT NULL,
        key BIGINT NOT NULL,
        safety_type TEXT NOT NULL,
        event TEXT NOT NULL,
        phase TEXT,
        options_json TEXT NOT NULL,
        audio_url TEXT,
        version_label TEXT,
        attribute_reason TEXT,
        card_code TEXT,
        title TEXT,
        guide_text TEXT,
        from_version_id BIGINT,
        released_by BIGINT,
        released_at BIGINT NOT NULL DEFAULT ${NOW_MS}
      );
    `);

        await this.run(`
      CREATE TABLE IF NOT EXISTS card_groups (
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name TEXT NOT NULL,
        description TEXT,
        released_ids_json TEXT NOT NULL,
        is_default INTEGER DEFAULT 0,
        max_scores_json TEXT,
        created_by BIGINT,
        created_at BIGINT NOT NULL DEFAULT ${NOW_MS},
        updated_at BIGINT
      );
    `);
        await this.run(`CREATE INDEX IF NOT EXISTS idx_card_groups_default ON card_groups(is_default);`);

        // 向后兼容：为已存在的表补 2026 卡牌包新增列（PG 9.6+ 支持 IF NOT EXISTS）
        const pgAdds = [
            ["cards", "card_code TEXT"],
            ["cards", "workbench TEXT DEFAULT '经典版'"],
            ["cards", "title TEXT"],
            ["cards", "guide_text TEXT"],
            ["cards", "subtopic TEXT"],
            ["cards", "whitepaper_ref TEXT"],
            ["cards", "trainer_material_json TEXT"],
            ["card_versions", "card_code TEXT"],
            ["card_versions", "workbench TEXT"],
            ["card_versions", "title TEXT"],
            ["card_versions", "guide_text TEXT"],
            ["card_versions", "subtopic TEXT"],
            ["card_versions", "whitepaper_ref TEXT"],
            ["card_versions", "trainer_material_json TEXT"],
            ["cards_released", "card_code TEXT"],
            ["cards_released", "title TEXT"],
            ["cards_released", "guide_text TEXT"],
        ];
        for (const [table, def] of pgAdds) {
            try { await this.run(`ALTER TABLE ${table} ADD COLUMN IF NOT EXISTS ${def}`); }
            catch (e) { /* 列已存在或不支持，忽略 */ }
        }
        // 现有卡牌归入「经典版」工作台
        try { await this.run(`UPDATE cards SET workbench='经典版' WHERE workbench IS NULL`); } catch (e) {}

        console.log(`✅ [PostgreSQL] Cards database initialized`);
    }

    async close() {
        const pool = this.pool;
        this.pool = null;
        this.api = null;
        if (pool) await pool.end();
    }

    run(sql, params = []) { return this.api.run(sql, params); }
    get(sql, params = []) { return this.api.get(sql, params); }
    all(sql, params = []) { return this.api.all(sql, params); }
}

/**
 * SQLite 数据源实现
 */
class SQLiteCardsSource extends ICardsSource {
    constructor(dbPath) {
        super();
        this.dbPath = dbPath;
        this.db = null;
    }

    async close() {
        const db = this.db;
        this.db = null;
        if (db) await new Promise((resolve, reject) => db.close(err => err ? reject(err) : resolve()));
    }

    async init() {
        const dir = path.dirname(this.dbPath);
        if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

        this.db = new sqlite3.Database(this.dbPath);

        // Schema 定义
        await this.run(`
      CREATE TABLE IF NOT EXISTS cards (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        key INTEGER UNIQUE NOT NULL,
        safety_type TEXT NOT NULL,
        event TEXT NOT NULL,
        phase TEXT,
        options_json TEXT NOT NULL,
        status TEXT DEFAULT 'pending',
        version INTEGER DEFAULT 1,
        attribute_reason TEXT,
        created_at INTEGER NOT NULL DEFAULT (strftime('%s','now')*1000),
        updated_at INTEGER,
        deleted_at INTEGER
      );
    `);

        // 创建卡牌历史版本表
        await this.run(`
      CREATE TABLE IF NOT EXISTS card_versions (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        card_id INTEGER NOT NULL,
        key INTEGER NOT NULL,
        safety_type TEXT NOT NULL,
        event TEXT NOT NULL,
        phase TEXT,
        options_json TEXT NOT NULL,
        status TEXT DEFAULT 'pending',
        version INTEGER DEFAULT 1,
        version_label TEXT,
        attribute_reason TEXT,
        author_id INTEGER,
        created_at INTEGER NOT NULL DEFAULT (strftime('%s','now')*1000)
      );
    `);

        // 创建游戏发布快照表（前端读取）
        await this.run(`
      CREATE TABLE IF NOT EXISTS cards_released (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        card_id INTEGER NOT NULL,
        key INTEGER NOT NULL,
        safety_type TEXT NOT NULL,
        event TEXT NOT NULL,
        phase TEXT,
        options_json TEXT NOT NULL,
        audio_url TEXT,
        version_label TEXT,
        attribute_reason TEXT,
        from_version_id INTEGER,
        released_by INTEGER,
        released_at INTEGER NOT NULL DEFAULT (strftime('%s','now')*1000)
      );
    `);

        // 创建卡牌组表（按版本/套装组织发布快照）
        await this.run(`
      CREATE TABLE IF NOT EXISTS card_groups (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        name TEXT NOT NULL,
        description TEXT,
        released_ids_json TEXT NOT NULL,
        is_default INTEGER DEFAULT 0,
        created_by INTEGER,
        created_at INTEGER NOT NULL DEFAULT (strftime('%s','now')*1000),
        updated_at INTEGER
      );
    `);
        await this.run(`CREATE INDEX IF NOT EXISTS idx_card_groups_default ON card_groups(is_default);`);

        // 向后兼容：添加可能缺失的列
        const missingColumns = [
            { name: 'status', def: 'TEXT DEFAULT "pending"' },
            { name: 'version', def: 'INTEGER DEFAULT 1' },
            { name: 'updated_at', def: 'INTEGER' },
            { name: 'deleted_at', def: 'INTEGER' },
            { name: 'branch', def: 'TEXT DEFAULT "release"' },
            { name: 'online_id', def: 'TEXT' },
            { name: 'parent_id', def: 'INTEGER' },
            { name: 'notes', def: 'TEXT' },
            { name: 'version_label', def: 'TEXT' },
            { name: 'audio_url', def: 'TEXT' },
            { name: 'current_version_id', def: 'INTEGER' },
            { name: 'author_id', def: 'INTEGER' },
            { name: 'attribute_reason', def: 'TEXT' },
            { name: 'card_code', def: 'TEXT' },
            { name: 'workbench', def: 'TEXT DEFAULT "经典版"' },
            { name: 'title', def: 'TEXT' },
            { name: 'guide_text', def: 'TEXT' },
            { name: 'subtopic', def: 'TEXT' },
            { name: 'whitepaper_ref', def: 'TEXT' },
            { name: 'trainer_material_json', def: 'TEXT' }
        ];

        const missingVersionColumns = [
            { name: 'author_id', def: 'INTEGER' },
            { name: 'audio_url', def: 'TEXT' },
            { name: 'note', def: 'TEXT' },
            { name: 'branch', def: 'TEXT DEFAULT "main"' },
            { name: 'parent_id', def: 'INTEGER' },
            { name: 'promoted_at', def: 'INTEGER' },
            { name: 'attribute_reason', def: 'TEXT' },
            { name: 'card_code', def: 'TEXT' },
            { name: 'workbench', def: 'TEXT' },
            { name: 'title', def: 'TEXT' },
            { name: 'guide_text', def: 'TEXT' },
            { name: 'subtopic', def: 'TEXT' },
            { name: 'whitepaper_ref', def: 'TEXT' },
            { name: 'trainer_material_json', def: 'TEXT' }
        ];

        for (const col of missingColumns) {
            try {
                await this.run(`ALTER TABLE cards ADD COLUMN ${col.name} ${col.def}`);
            } catch (e) {
                // 列已存在，忽略错误
            }
        }

        for (const col of missingVersionColumns) {
            try {
                await this.run(`ALTER TABLE card_versions ADD COLUMN ${col.name} ${col.def}`);
            } catch (e) {
                // 列已存在，忽略错误
            }
        }

        // card_groups 表补全缺失列
        const missingGroupColumns = [
            { name: 'max_scores_json', def: 'TEXT' }
        ];
        for (const col of missingGroupColumns) {
            try {
                await this.run(`ALTER TABLE card_groups ADD COLUMN ${col.name} ${col.def}`);
            } catch (e) { /* 列已存在 */ }
        }

        const missingReleasedColumns = [
            { name: 'attribute_reason', def: 'TEXT' },
            { name: 'card_code', def: 'TEXT' },
            { name: 'title', def: 'TEXT' },
            { name: 'guide_text', def: 'TEXT' }
        ];

        for (const col of missingReleasedColumns) {
            try {
                await this.run(`ALTER TABLE cards_released ADD COLUMN ${col.name} ${col.def}`);
            } catch (e) {
                // 列已存在，忽略错误
            }
        }

        // 现有卡牌归入「经典版」工作台
        try { await this.run(`UPDATE cards SET workbench='经典版' WHERE workbench IS NULL`); } catch (e) {}

        console.log(`✅ [SQLite] Cards database initialized: ${this.dbPath}`);
    }

    run(sql, params = []) {
        return new Promise((resolve, reject) => {
            this.db.run(sql, params, function (err) {
                if (err) reject(err);
                else resolve({ lastID: this.lastID, changes: this.changes });
            });
        });
    }

    get(sql, params = []) {
        return new Promise((resolve, reject) => {
            this.db.get(sql, params, (err, row) => {
                if (err) reject(err);
                else resolve(row);
            });
        });
    }

    all(sql, params = []) {
        return new Promise((resolve, reject) => {
            this.db.all(sql, params, (err, rows) => {
                if (err) reject(err);
                else resolve(rows);
            });
        });
    }
}

/**
 * 飞书多维表格数据源实现 (占位符)
 */
class FeishuCardsSource extends ICardsSource {
    constructor(appId, appSecret, appToken, tableId) {
        super();
        this.appId = appId;
        this.appSecret = appSecret;
        this.appToken = appToken;
        this.tableId = tableId;
        this.tenantAccessToken = null;
    }

    async init() {
        console.log(`✅ [Feishu] Initializing connection to Base: ${this.appToken}`);
        // TODO: 实现飞书认证和连接
    }

    async run(sql, params) {
        // TODO: 解析SQL并转换为飞书API调用 (增删改)
        console.log("[Feishu] Mock run:", sql, params);
        return { lastID: 0, changes: 1 };
    }

    async get(sql, params) {
        // TODO: 解析SQL并转换为飞书API调用 (查询单条)
        console.log("[Feishu] Mock get:", sql, params);
        return null;
    }

    async all(sql, params) {
        // TODO: 解析SQL并转换为飞书API调用 (查询列表)
        console.log("[Feishu] Mock all:", sql, params);
        return [];
    }
}

// --- 工厂模式 & 单例 ---

let currentSource = null;

export async function initCardsDb({ source, connectionString, sqlitePath } = {}) {
    if (currentSource) throw new Error("Cards database is already initialized; close it before restarting.");
    const sourceType = source || process.env.CARDS_SOURCE || 'postgres'; // 'postgres' | 'sqlite' | 'feishu'

    if (sourceType === 'feishu') {
        currentSource = new FeishuCardsSource(
            process.env.FEISHU_APP_ID,
            process.env.FEISHU_APP_SECRET,
            process.env.FEISHU_APP_TOKEN,
            process.env.FEISHU_TABLE_ID
        );
    } else if (sourceType === 'sqlite') {
        const dbPath = sqlitePath || process.env.CARDS_DB_PATH || "./data/cards.db";
        currentSource = new SQLiteCardsSource(dbPath);
    } else {
        // 卡牌表与主库表名不冲突，默认复用主库连接串（同一个 PG database）
        const conn = connectionString || process.env.CARDS_DATABASE_URL || process.env.DATABASE_URL ||
            "postgres://postgres:postgres@localhost:5432/wqt";
        currentSource = new PostgresCardsSource(conn);
    }

    await currentSource.init();
}

// 导出与旧接口兼容的方法
export async function closeCardsDb() {
    const source = currentSource;
    currentSource = null;
    if (source) await source.close();
}

export function cardsDbRun(sql, params) { return currentSource.run(sql, params); }
export function cardsDbGet(sql, params) { return currentSource.get(sql, params); }
export function cardsDbAll(sql, params) { return currentSource.all(sql, params); }
