'use strict';
// Presentation-only demo state. No production requests or microphone access.
Object.assign(state,{attributes:[3,3,3,3,3],audit:[],skills:[false,false,false,false,false],accountTab:0,displayName:'守望者',reviewOpen:false,recording:'未开启',applications:[],feedbacks:[],learning:false});
const accountTabs=['账户资料','权益与期限','安全设置','我的学习','活动码','文件与反馈'];
const skillLetters=['R','A','S','P','E'];
const safe=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const activeSession=()=>Boolean(state.sessionId&&!state.ended);
const writable=()=>activeSession()&&!state.paused;
const statusText=()=>!state.sessionId?'未开始':state.ended?'已结束':state.paused?'已暂停':'进行中';
const phaseCompleted=i=>state.history.filter(h=>h.phase===i).length;
function productPage(){
  return `<header class="app-header"><div class="brand"><img src="assets/logo.png" alt="伍力全开"><div><strong>AI@5000days</strong><small>《伍力全开》桌游计分系统</small></div></div><nav class="main-nav" aria-label="主导航">${['桌游模式','监督模式','我的'].map((t,i)=>btn(`<small>${['PLAY','WATCH','ME'][i]}</small>${t}`,`nav:${i}`,state.nav===i?'active':'')).join('')}</nav><div class="identity"><div class="timer"><small>${statusText()}</small><strong data-clock>${state.sessionId?timeText():'— —'}</strong></div><div class="avatar">守</div><div>${safe(state.displayName)}<small>离线演示账号</small></div></div></header><div class="sync"><span>当前位置　${['桌游模式','监督模式','我的'][state.nav]}</span><span class="success">● ${state.sessionId?'本局 '+state.sessionId.slice(0,8):'等待开启新游戏'}</span><span class="cyan">原型演示 · 不连接生产服务</span></div>${state.nav===0?gamePage():state.nav===1?watchPage():accountPage()}`;
}
function gamePage(){return `<div class="workbench"><aside class="sidebar" aria-label="桌游工具栏">${['本局游戏状态','伍力技能','现场督导'].map((t,i)=>`<button class="side-btn" data-action="side:${i}" aria-expanded="${state.side===i}"><span class="number">0${i+1}</span>${t}<span class="chevron">${state.side===i?'×':'⌄'}</span></button>`).join('')}${state.side>=0?railPanel(state.side):''}<div class="side-bottom">${btn(state.paused?'恢复游戏':'暂停游戏','pause','',!activeSession())}${btn('停止并复盘','stop','danger',!activeSession())}</div></aside><section class="main-area">${state.reviewOpen?reviewPage():`<div class="reader"><input id="card-code" aria-label="卡牌编号" placeholder="输入卡牌编号，如 B01" value="${safe(state.card?.code||'')}" ${writable()?'':'disabled'}>${btn('选择卡牌','picker','',!writable())}${btn('新游戏','new-game','primary',activeSession())}</div><div class="content">${state.card?cardView():`<div class="empty"><img src="assets/banner-bg.png" alt="品牌场景"><div class="eyebrow">DECISION DECK</div><h1>下一张情景牌<br>正在等你开启</h1><p>${state.sessionId?(state.ended?'本局已结束，可查看复盘或开启新游戏':'输入卡牌编号，或从牌库选择'):'从上方「新游戏」选择现场活动'}</p>${state.ended?btn('查看本局复盘','review'):''}</div>`}${state.ended&&state.card?`<div class="completion">本局已完成 · 最后一张反馈保留 ${btn('查看复盘','review')}${btn('新游戏','new-game')}</div>`:''}</div>`}</section></div>`}
function railPanel(i){
  const title=['本局游戏状态','伍力技能','现场督导'][i];
  let body='';
  if(i===0)body=`${[['活动',state.sessionId?activities[state.activity][0]:'尚未开始'],['当前卡牌',state.card?.code||'尚未读取'],['模式',state.sessionId?currentConfig().mode:'—']].map(([k,v])=>`<div class="metric"><span>${k}</span><b>${v}</b></div>`).join('')}${phases.map((p,j)=>`<div class="phase-progress"><div>${p}<b>${phaseCompleted(j)} / ${state.sessionId?state.counts[j]:'—'}</b></div><progress max="${state.counts[j]||1}" value="${phaseCompleted(j)}"></progress></div>`).join('')}`;
  if(i===1)body=`<p class="muted">数智技能 · 每局使用状态</p>${powers.map((p,j)=>`<div class="skill-row"><span class="number">${skillLetters[j]}</span><span>${p}<small>${state.skills[j]?'已演示使用':'未使用'}</small></span>${btn('查看',`skill:${j}`)}</div>`).join('')}<p class="muted">展示名称与本局使用状态；技能效果尚未接入，不修改正式分值。</p>`;
  if(i===2)body=`<div class="metric"><span>录音状态</span><b>${state.recording}</b></div><div class="wave">▁▃▂▁▅▃▂▁▃▂▁</div><p>开启前会请求麦克风权限</p><p class="muted">本原型仅演示授权/拒绝/停止状态，不读取麦克风，不上传录音。</p>${btn(state.recording==='演示录音中'?'停止现场录音':'开始现场录音','record-demo')}${btn('查看监督模式','nav:1','link')}`;
  return `<section class="rail-flyout" aria-label="${title}"><div class="panel-heading"><h3>${title}</h3>${btn('×','close-rail')}</div>${body}</section>`;
}
function radar(){const point=(i,r)=>[170+Math.sin(i*2*Math.PI/5)*r,155-Math.cos(i*2*Math.PI/5)*r];const points=r=>powers.map((_,i)=>point(i,r).join(',')).join(' ');return `<svg viewBox="0 0 340 310" role="img" aria-label="五维当前属性：${state.attributes.join('、')}">${[25,50,75,100].map(r=>`<polygon points="${points(r)}" fill="none" stroke="#364776"/>`).join('')}${powers.map((p,i)=>{const [x,y]=point(i,132),[a,b]=point(i,100);return `<line x1="170" y1="155" x2="${a}" y2="${b}" stroke="#364776"/><text x="${x}" y="${y}" fill="#c9d2ee" text-anchor="middle" font-size="13">${p}</text>`}).join('')}<polygon points="${state.attributes.map((v,i)=>point(i,v*10).join(',')).join(' ')}" fill="#09d6f533" stroke="#09d6f5" stroke-width="2.5"/>${state.attributes.map((v,i)=>{const [x,y]=point(i,v*10);return `<circle cx="${x}" cy="${y}" r="4" fill="#09d6f5"/>`}).join('')}</svg>`}
function watchPage(){return `<main class="wide-page supervision"><div class="page-heading"><div><div class="eyebrow">WATCH · LIVE SESSION</div><h1>监督模式</h1><p class="muted">与桌游模式共享同一局 · 守望者现场辅助</p></div><span class="badge">${statusText()}</span></div><div class="watch-grid"><div><section class="surface"><h2>伍力属性雷达图</h2>${radar()}<p class="muted">${state.sessionId?'当前演示局属性':'尚未开始新游戏 · 展示初始值'}</p></section><section class="surface"><h2>游戏状态</h2><div class="metric">状态<b>${statusText()}</b></div><div class="metric">当前阶段<b>${state.sessionId?phases[state.phase]:'—'}</b></div><div class="metric">剩余时间<b data-clock>${state.sessionId?timeText():'—'}</b></div><div class="metric">已完成卡牌<b>${state.history.length}</b></div></section></div><div><section class="surface"><h2>伍力控制面板</h2><p class="muted">原型属性调整，范围 0–10；暂停或结束后锁定。</p>${powers.map((p,i)=>`<div class="attribute-row"><span><b class="skill-letter">${skillLetters[i]}</b>${p}</span><div class="attribute-input">${btn('−',`attribute:${i}:-1`,'',!writable()||state.attributes[i]===0)}<input type="number" min="0" max="10" value="${state.attributes[i]}" data-attribute="${i}" aria-label="${p}数值" ${writable()?'':'disabled'}>${btn('+',`attribute:${i}:1`,'',!writable()||state.attributes[i]===10)}</div></div>`).join('')}</section><section class="surface"><h2>操作历史</h2><div class="audit-list">${state.audit.length?state.audit.slice().reverse().map(a=>`<div class="metric"><span>${safe(a.text)}</span><small>${a.time}</small></div>`).join(''):'<p class="muted">尚无操作。开始游戏后，记录卡牌选择与属性调整。</p>'}</div><div class="actions">${btn('重置属性','reset-attributes','danger',!writable())}${btn('导出数据','export-session','',!state.sessionId)}</div></section></div></div></main>`}
function accountPage(){return `<main class="wide-page account"><section class="profile-hero"><div class="avatar large">守</div><div><div class="eyebrow">WATCHER PROFILE · 守望者档案</div><h1>${safe(state.displayName)}</h1><p class="muted">AI 5000天 · 演示组织</p></div><div class="profile-badges"><span class="badge">账号有效（示例）</span><span class="badge">组织成员</span></div></section><div class="account-grid"><nav class="account-nav" aria-label="账号内部导航">${accountTabs.map((t,i)=>`<button data-action="account:${i}" class="${state.accountTab===i?'active':''}" aria-current="${state.accountTab===i?'page':'false'}"><span>${['人','章','盾','学','码','件'][i]}</span>${t}<b>›</b></button>`).join('')}</nav><section class="surface account-content"><div class="eyebrow">${accountTabs[state.accountTab]}</div>${accountBody()}</section></div></main>`}
function accountBody(){switch(state.accountTab){
case 0:return `<div class="panel-heading"><h1>基本信息</h1>${btn('编辑资料','edit-profile')}</div><div class="info-grid">${[['守望者名',state.displayName],['所属组织','AI 5000天 · 演示组织'],['账号角色','守望者'],['绑定手机',state.phone?state.phone.slice(0,3)+' **** '+state.phone.slice(-4):'未绑定']].map(([k,v])=>`<div><small>${k}</small><strong>${safe(v)}</strong></div>`).join('')}</div><p class="muted">修改仅保留在当前原型窗口，不更新真实账号。</p>`;
case 1:return `<h1>权益与期限</h1><div class="info-grid"><div><small>账号状态</small><strong>有效（演示）</strong></div><div><small>有效期来源</small><strong>由所属组织统一管理</strong></div><div><small>组织有效期</small><strong>未连接真实数据</strong></div><div><small>个人有效期</small><strong>组织成员不单独设定</strong></div></div><p>可使用桌游计分、监督模式及账号已有学习内容。</p><p class="muted">到期/停用状态应由正式账号服务提供；本页不伪造真实期限。</p>`;
case 2:return `<h1>安全设置</h1><form data-form="password"><label>当前密码<input id="old-password" type="password" required autocomplete="off"></label><label>新密码<input id="new-password" type="password" minlength="6" required autocomplete="off"></label><label>确认新密码<input id="confirm-password" type="password" minlength="6" required autocomplete="off"></label><button class="primary" type="submit">检查密码格式（演示）</button><p role="status" id="password-message"></p></form><p class="muted">不验证旧密码、不保存密码、不修改真实账号。</p>${btn('退出登录','signout','danger')}`;
case 3:return `<h1>我的学习</h1><p class="muted">学习内容应沿用既有服务。以下为可操作的示例，不代表正式课程。</p><div class="learning-card"><div class="eyebrow">示例学习内容</div><h2>守望者现场操作指南</h2><p>线下参与、活动配置、计分反馈与复盘边界。</p><span class="badge">${state.learning?'已阅读（本地）':'未阅读'}</span>${btn('打开学习内容','learn')}</div>`;
case 4:return `<h1>我的活动码</h1><p class="muted">申请及状态仅作演示。已通过活动才展示五位活动码。</p><form data-form="activity" class="inline-form"><label>活动名称<input id="request-name" required maxlength="60" placeholder="请输入活动名称"></label><label>活动地点<input id="request-place" required maxlength="60" placeholder="请输入活动地点"></label><button type="submit" class="primary">提交演示申请</button></form><h2>我发起的活动</h2>${[['未来守望者 · 城市站','已通过','WQTAY'],['数智安全体验营','待审批',''],['社区体验活动','已拒绝','']].concat(state.applications.map(a=>[a.name,'待审批',''])).map(([name,status,code])=>`<div class="application-row"><div><strong>${safe(name)}</strong><small>${status==='已拒绝'?'示例原因：请补充活动地点':code?code:'审批通过后显示活动码'}</small></div><span class="badge">${status}</span>${code?btn('复制','copy-code'):''}</div>`).join('')}<h2>活动记录</h2>${state.sessionId?`<div class="application-row"><div>${activities[state.activity??0][0]}<small>本局 ${state.sessionId.slice(0,8)} · ${statusText()} · ${state.history.length} 张</small></div>${btn('查看本局记录 / 复盘','review')}</div>`:'<p class="muted">暂无场次，开始新游戏后显示。</p>'}<h2>查询活动</h2><form data-form="lookup" class="inline-form"><label>活动码<input id="lookup-code" maxlength="5" placeholder="WQTAY" required></label><button type="submit">查询示例活动</button></form><p id="lookup-result" role="status"></p>`;
case 5:return `<h1>文件与反馈</h1><h2>我的文件</h2><div class="empty-files">暂无已上传文件 · 未连接文件服务</div><h2>提交反馈</h2><form data-form="feedback"><label>反馈内容<textarea id="feedback-text" rows="5" maxlength="500" required placeholder="描述问题或建议"></textarea></label><button class="primary" type="submit">保存演示反馈</button></form>${state.feedbacks.map(t=>`<div class="application-row"><span>${safe(t)}</span><small>仅本地保存</small></div>`).join('')}`;
}}
function reviewPage(){return `<div class="content review-content"><div class="panel-heading"><div><div class="eyebrow">SESSION REVIEW</div><h1>本局记录与复盘</h1></div>${btn('返回桌游','leave-review')}</div><p>${state.sessionId?'本局 '+state.sessionId.slice(0,8):'暂无本局'} · ${statusText()} · ${state.history.length} 张</p>${state.history.map(h=>`<div class="metric"><span>${h.code} · ${phases[h.phase]}</span><b>选择 ${'ABC'[h.choice]}</b></div>`).join('')||'<p class="muted">尚无已完成卡牌。</p>'}<h2>既有复盘链路</h2><ol class="review-steps"><li>读取本局记录</li><li>检查最低卡牌数</li><li>生成成长报告</li><li>上传报告</li><li>查看 / 导出海报</li></ol><p class="muted">未连接现有 game-review.js 报告服务；不会用选择历史或演示数据伪造正式报告。</p>${btn('导出演示记录（非报告）','export-session','',!state.sessionId)}${btn('新游戏','new-game','primary',activeSession())}</div>`}
function logChange(text){state.audit.push({text,time:new Date().toLocaleTimeString()});save()}
function changeAttribute(i,value){if(!writable())return;const n=Number(value);if(!Number.isFinite(n)){render();return}const next=Math.max(0,Math.min(10,n)),old=state.attributes[i];state.attributes[i]=next;if(old!==next)logChange(`${powers[i]} ${old} → ${next}`);render()}
function exportSession(){const data={notice:'离线原型数据，非正式复盘报告',sessionId:state.sessionId,activity:state.activity===null?null:activities[state.activity],attributes:state.attributes,history:state.history,audit:state.audit};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='wqt-session-demo.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
document.addEventListener('change',e=>{if(e.target.matches('[data-attribute]'))changeAttribute(+e.target.dataset.attribute,e.target.value)});
document.addEventListener('submit',e=>{
  const form=e.target.closest('[data-form]');if(!form)return;e.preventDefault();
  if(form.dataset.form==='password'){$('#password-message').textContent=$('#new-password').value!==$('#confirm-password').value?'两次密码不一致':'格式检查通过；未修改真实密码';form.reset()}
  if(form.dataset.form==='activity'){const name=$('#request-name').value.trim(),place=$('#request-place').value.trim();if(!name||!place)return;state.applications.push({name,place});render();toast('演示申请已保存至本页，未提交服务端')}
  if(form.dataset.form==='feedback'){const value=$('#feedback-text').value.trim();if(!value)return;state.feedbacks.push(value);render()}
  if(form.dataset.form==='lookup')$('#lookup-result').textContent=$('#lookup-code').value.trim().toUpperCase()==='WQTAY'?'未来守望者 · 城市站 / 上海 · 当前开放（示例）':'未找到此活动码';
  if(form.dataset.form==='profile'){const name=$('#display-name').value.trim();if(!name)return;state.displayName=name;overlay.innerHTML='';render()}
});
document.addEventListener('click',e=>{
  const el=e.target.closest('[data-action]');if(!el||el.disabled)return;const [a,v,w]=el.dataset.action.split(':');
  const handled=['account','attribute','reset-attributes','confirm-reset','close-rail','skill','skill-demo','record-demo','record-allow','record-deny','export-session','edit-profile','learn','learn-done','copy-code','signout','confirm-signout','leave-review'];
  if(!handled.includes(a))return;e.stopImmediatePropagation();
  if(a==='account'){state.accountTab=+v;render()}
  if(a==='attribute')changeAttribute(+v,state.attributes[+v]+Number(w));
  if(a==='close-rail'){const prev=state.side;state.side=-1;render();document.querySelector(`[data-action="side:${prev}"]`)?.focus()}
  if(a==='reset-attributes')show('<h2>重置本局属性？</h2><p>将五维恢复为 3；保留本局卡牌记录，并记录此次重置。仅修改演示局。</p>'+btn('取消','close')+btn('确认重置','confirm-reset','danger'));
  if(a==='confirm-reset'&&writable()){state.attributes=[3,3,3,3,3];logChange('重置五维属性为 3');overlay.innerHTML='';render()}
  if(a==='skill')show(`<h2>${skillLetters[+v]} · ${powers[+v]}数智技能</h2><p>本原型展示使用状态；正式技能效果待接入，不修改分值。</p>${btn('演示使用状态',`skill-demo:${v}`,'primary',!writable()||state.skills[+v])}`);
  if(a==='skill-demo'&&writable()&&!state.skills[+v]){state.skills[+v]=true;logChange('演示使用 '+powers[+v]+' 技能（未应用效果）');overlay.innerHTML='';state.side=1;render()}
  if(a==='record-demo'){if(state.recording==='演示录音中'){state.recording='已停止（演示）';render()}else show('<h2>麦克风权限 · 状态演示</h2><p>不会请求设备麦克风。请选择要查看的授权状态。</p>'+btn('模拟拒绝','record-deny')+btn('模拟允许','record-allow','primary'))}
  if(a==='record-allow'||a==='record-deny'){state.recording=a==='record-allow'?'演示录音中':'权限被拒绝（演示）';overlay.innerHTML='';state.side=2;render()}
  if(a==='export-session'&&state.sessionId)exportSession();
  if(a==='edit-profile')show(`<h2>编辑资料</h2><form data-form="profile"><label>守望者名<input id="display-name" value="${safe(state.displayName)}" maxlength="30" required></label><button type="submit" class="primary">保存本地资料</button></form>`);
  if(a==='learn')show('<h2>守望者现场操作指南（示例）</h2><p>由守望者登录操作，其他玩家在线下参与。</p><p>新游戏选择已有活动，按活动配置分配三个阶段的数量。进入游戏后选卡获取反馈。</p><p>结束后沿既有复盘链路查看本局报告。</p>'+btn('标记已阅读（本地）','learn-done','primary'));
  if(a==='learn-done'){state.learning=true;overlay.innerHTML='';render()}
  if(a==='copy-code'){navigator.clipboard?.writeText('WQTAY').then(()=>toast('已复制 WQTAY')).catch(()=>toast('复制失败，请手动复制 WQTAY'));if(!navigator.clipboard)toast('请手动复制 WQTAY')}
  if(a==='signout')show('<h2>退出离线演示？</h2><p>清除本窗口演示状态，不调用生产退出接口。</p>'+btn('取消','close')+btn('确认退出','confirm-signout','danger'));
  if(a==='confirm-signout'){try{sessionStorage.removeItem('wqt-prototype-session')}catch{} location.reload()}
  if(a==='leave-review'){state.nav=0;state.reviewOpen=false;render()}
},true);
